TST Test using master

diff --git a/azure/posix-sdist.yml b/azure/posix-sdist.yml
--- a/azure/posix-sdist.yml
+++ b/azure/posix-sdist.yml
@@ -26,6 +26,7 @@ jobs:
               SKIP_BUILD="true"
             fi
           fi
+          BUILD_COMMIT=$NIGHTLY_BUILD_COMMIT
 
           echo "Building scikit-learn@$BUILD_COMMIT"
           echo "##vso[task.setvariable variable=BUILD_COMMIT]$BUILD_COMMIT"
@@ -86,3 +87,44 @@ jobs:
           testRunTitle: ${{ format('{0}-$(Agent.JobName)', 'Linux_Source_Dist') }}
         displayName: "Publish Test Results"
         condition: eq(variables['SKIP_BUILD'], 'false')
+
+      - bash: |
+          echo "##vso[task.prependpath]$CONDA/bin"
+          sudo chown -R $USER $CONDA
+        displayName: Add conda to PATH
+        condition: and(succeeded(), eq(variables['SKIP_BUILD'], 'false'), ne(variables['Build.Reason'], 'PullRequest'))
+
+      - bash: conda install -q -y anaconda-client
+        displayName: Install anaconda-client
+        condition: and(succeeded(), eq(variables['SKIP_BUILD'], 'false'), ne(variables['Build.Reason'], 'PullRequest'))
+
+      - bash: |
+          set -e
+          if [ "$BUILD_REASON" == "Schedule" ]; then
+            ANACONDA_ORG="scipy-wheels-nightly"
+            TOKEN="$SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN"
+          else
+            ANACONDA_ORG="scikit-learn-wheels-staging"
+            TOKEN="$SCIKIT_LEARN_STAGING_UPLOAD_TOKEN"
+          fi
+          if [ "$TOKEN" == "" ]; then
+            echo "##[warning] Could not find anaconda.org upload token in secret variables"
+          fi
+          echo "##vso[task.setvariable variable=TOKEN]$TOKEN"
+          echo "##vso[task.setvariable variable=ANACONDA_ORG]$ANACONDA_ORG"
+        displayName: Retrieve secret upload token
+        condition: and(succeeded(), eq(variables['SKIP_BUILD'], 'false'), ne(variables['Build.Reason'], 'PullRequest'))
+        env:
+          # Secret variables need to mapped to env variables explicitly:
+          SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN: $(SCIKIT_LEARN_NIGHTLY_UPLOAD_TOKEN)
+          SCIKIT_LEARN_STAGING_UPLOAD_TOKEN: $(SCIKIT_LEARN_STAGING_UPLOAD_TOKEN)
+
+      - bash: |
+          set -e
+          # The --force option forces a replacement if the remote file already
+          # exists.
+          ls wheelhouse/*.whl
+          anaconda -t $TOKEN upload --force -u $ANACONDA_ORG wheelhouse/*.whl
+          echo "PyPI-style index: https://pypi.anaconda.org/$ANACONDA_ORG/simple"
+        displayName: Upload to anaconda.org (only if secret token is retrieved)
+        condition: ne(variables['TOKEN'], '')
